// =============================================================================
// ProactiveInsight
// =============================================================================

/// A single contextual insight or nudge generated by the [ProactiveEngine].
class ProactiveInsight {
  /// Human-readable message shown to the user.
  final String message;

  /// Insight category: nutrition, training, recovery, motivation, reminder.
  final String category;

  /// Priority score from 0.0 (low) to 1.0 (urgent). Used to rank and cap
  /// the number of insights displayed.
  final double priority;

  /// Optional action the UI can wire up (e.g. navigate to a screen).
  /// Values: log_meal, log_workout, view_progress, generate_plan, view_exercises.
  final String? actionType;

  /// Short label for the action button (e.g. "Log a meal").
  final String? actionLabel;

  const ProactiveInsight({
    required this.message,
    required this.category,
    required this.priority,
    this.actionType,
    this.actionLabel,
  });

  @override
  String toString() =>
      'ProactiveInsight(category: $category, priority: $priority, message: $message)';
}

// =============================================================================
// ProactiveEngine
// =============================================================================

/// Generates intelligent, contextual insights and nudges based on the user's
/// nutrition, training, and body-metric data combined with the current time of
/// day and known behaviour patterns.
///
/// All methods are pure functions over a [context] map so the engine carries no
/// mutable state and is trivially testable.
class ProactiveEngine {
  const ProactiveEngine();

  // ── Public API ─────────────────────────────────────────────────────────

  /// Generate up to [maxInsights] contextual insights, sorted by priority
  /// (highest first).
  List<ProactiveInsight> generateInsights({
    required Map<String, dynamic> context,
    int maxInsights = 3,
  }) {
    final all = <ProactiveInsight>[
      ..._nutritionInsights(context),
      ..._trainingInsights(context),
      ..._bodyMetricInsights(context),
      ..._timeBasedInsights(context),
      ..._motivationInsights(context),
      ..._recoveryInsights(context),
    ];

    // Sort descending by priority, then cap.
    all.sort((a, b) => b.priority.compareTo(a.priority));
    return all.take(maxInsights).toList();
  }

  /// Check whether a specific nudge type should fire given the current context.
  ///
  /// Supported [nudgeType] values:
  /// - `log_meal` - user hasn't eaten in a while
  /// - `log_workout` - behind on weekly target
  /// - `protein_warning` - significant protein deficit late in the day
  /// - `calorie_overage` - exceeded daily calorie target
  /// - `hydration_reminder` - generic afternoon hydration cue
  bool shouldNudge(String nudgeType, Map<String, dynamic> context) {
    final now = DateTime.now();
    final hour = now.hour;

    switch (nudgeType) {
      case 'log_meal':
        return _hoursSinceLastMeal(context) >= 5 && hour >= 10;
      case 'log_workout':
        final done = _intOr(context, 'workoutsThisWeek', 0);
        final target = _intOr(context, 'workoutDaysPerWeek', 4);
        final weekday = now.weekday; // 1=Mon ... 7=Sun
        final remaining = target - done;
        final daysLeft = 7 - weekday + 1;
        return remaining > 0 && remaining >= daysLeft;
      case 'protein_warning':
        final deficit = _proteinDeficit(context);
        return deficit > 30 && hour >= 15;
      case 'calorie_overage':
        final over = _calorieOverage(context);
        return over > 0;
      case 'hydration_reminder':
        return hour >= 13 && hour <= 17;
      default:
        return false;
    }
  }

  /// Return the single most relevant insight for this moment, or `null` if
  /// there is nothing worth showing.
  ProactiveInsight? getMostRelevantInsight(Map<String, dynamic> context) {
    final insights = generateInsights(context: context, maxInsights: 1);
    return insights.isNotEmpty ? insights.first : null;
  }

  // ── Nutrition insights ─────────────────────────────────────────────────

  List<ProactiveInsight> _nutritionInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];
    final hour = DateTime.now().hour;

    // 1. Protein deficit
    final proteinDeficit = _proteinDeficit(ctx);
    if (proteinDeficit > 10) {
      final isLate = hour >= 15;
      final grams = proteinDeficit.round();
      insights.add(ProactiveInsight(
        message: isLate
            ? "You're low on protein today \u2014 still need ${grams}g. "
              'Try a protein shake or chicken breast.'
            : "You have ${grams}g of protein left to hit your target today.",
        category: 'nutrition',
        priority: isLate ? 0.9 : 0.55,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    // 2. Calorie overage
    final calorieOver = _calorieOverage(ctx);
    if (calorieOver > 0) {
      insights.add(ProactiveInsight(
        message: "You're ${calorieOver.round()} kcal over your daily target. "
            'Consider lighter options for your remaining meals.',
        category: 'nutrition',
        priority: 0.65,
      ));
    }

    // 3. Fat overage
    final fatTarget = _doubleOr(ctx, 'fatsTarget', 0);
    final fatConsumed = _doubleOr(ctx, 'todayFats', 0);
    if (fatTarget > 0 && fatConsumed > fatTarget) {
      final overBy = (fatConsumed - fatTarget).round();
      insights.add(ProactiveInsight(
        message: "You're ${overBy}g over your fat target today. "
            'Opt for lean proteins and veggies for the rest of the day.',
        category: 'nutrition',
        priority: 0.6,
      ));
    }

    // 4. Carb deficit when training today
    final carbTarget = _doubleOr(ctx, 'carbsTarget', 0);
    final carbConsumed = _doubleOr(ctx, 'todayCarbs', 0);
    final carbDeficit = carbTarget - carbConsumed;
    final trainedToday = _trainedToday(ctx);
    if (carbDeficit > 40 && trainedToday && hour < 18) {
      insights.add(ProactiveInsight(
        message: 'You trained today but are ${carbDeficit.round()}g short on '
            'carbs. Refuel with rice, oats, or fruit to recover properly.',
        category: 'nutrition',
        priority: 0.7,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    // 5. No meals logged yet (late morning+)
    final mealsCount = _intOr(ctx, 'todayMealsCount', 0);
    if (mealsCount == 0 && hour >= 10) {
      insights.add(ProactiveInsight(
        message: hour >= 13
            ? "It's past noon and you haven't logged any meals. "
              "Don't let your nutrition go untracked!"
            : "Good morning! You haven't logged breakfast yet.",
        category: 'nutrition',
        priority: hour >= 13 ? 0.85 : 0.5,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    // 6. Haven't eaten in a long time
    final hoursSinceLastMeal = _hoursSinceLastMeal(ctx);
    if (hoursSinceLastMeal >= 6 && mealsCount > 0 && hour < 22) {
      insights.add(ProactiveInsight(
        message: "You haven't logged a meal in ${hoursSinceLastMeal.round()} "
            "hours. Don't forget to eat!",
        category: 'reminder',
        priority: 0.75,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    // 7. Close to calorie target (within 10%)
    final calTarget = _doubleOr(ctx, 'dailyCalorieTarget', 0);
    final calConsumed = _doubleOr(ctx, 'todayCalories', 0);
    final calRemaining = calTarget - calConsumed;
    if (calTarget > 0 &&
        calRemaining > 0 &&
        calRemaining <= calTarget * 0.10 &&
        hour >= 17) {
      insights.add(ProactiveInsight(
        message: "Almost there! Only ${calRemaining.round()} kcal left to hit "
            'your daily target.',
        category: 'motivation',
        priority: 0.45,
      ));
    }

    // 8. Very low calories consumed by afternoon (possible under-eating)
    if (calTarget > 0 && calConsumed < calTarget * 0.25 && hour >= 14) {
      insights.add(ProactiveInsight(
        message: "You've only consumed ${calConsumed.round()} kcal so far "
            "today \u2014 that's well below your ${calTarget.round()} kcal "
            'target. Make sure to fuel your body.',
        category: 'nutrition',
        priority: 0.8,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    return insights;
  }

  // ── Training insights ──────────────────────────────────────────────────

  List<ProactiveInsight> _trainingInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];
    final now = DateTime.now();
    final weekday = now.weekday; // 1=Mon ... 7=Sun

    final workoutsThisWeek = _intOr(ctx, 'workoutsThisWeek', 0);
    final workoutTarget = _intOr(ctx, 'workoutDaysPerWeek', 4);

    // 9. Behind on weekly workout target
    if (workoutTarget > 0 && workoutsThisWeek < workoutTarget) {
      final remaining = workoutTarget - workoutsThisWeek;
      final daysLeft = 7 - weekday + 1;

      if (remaining > 0 && daysLeft > 0) {
        final urgency = remaining / daysLeft; // >1 means behind schedule
        if (urgency >= 1.0) {
          insights.add(ProactiveInsight(
            message: 'You need $remaining more workout${remaining > 1 ? 's' : ''} '
                'this week with only $daysLeft day${daysLeft > 1 ? 's' : ''} '
                'left. Time to hit the gym!',
            category: 'training',
            priority: 0.85,
            actionType: 'log_workout',
            actionLabel: 'Start a workout',
          ));
        } else if (urgency >= 0.5) {
          insights.add(ProactiveInsight(
            message: "$remaining session${remaining > 1 ? 's' : ''} left to "
                'hit your weekly target. You got this!',
            category: 'training',
            priority: 0.5,
            actionType: 'log_workout',
            actionLabel: 'Start a workout',
          ));
        }
      }
    }

    // 10. Volume drop compared to last week
    final volumeChange = _doubleOr(ctx, 'weeklyVolumeChange', 0);
    if (volumeChange <= -20) {
      insights.add(ProactiveInsight(
        message: 'Your training volume dropped ${volumeChange.abs().round()}% '
            'this week compared to last week. Consider increasing intensity.',
        category: 'training',
        priority: 0.6,
        actionType: 'log_workout',
        actionLabel: 'Plan a workout',
      ));
    }

    // 11. Days since last workout
    final daysSinceWorkout = _daysSinceLastWorkout(ctx);
    if (daysSinceWorkout >= 4 && daysSinceWorkout < 14) {
      insights.add(ProactiveInsight(
        message: "It's been $daysSinceWorkout days since your last workout. "
            'A rest day or two is fine, but consistency is key!',
        category: 'training',
        priority: 0.7,
        actionType: 'log_workout',
        actionLabel: 'Start a workout',
      ));
    } else if (daysSinceWorkout >= 14) {
      insights.add(ProactiveInsight(
        message: "You haven't trained in ${daysSinceWorkout} days. "
            "It's okay \u2014 everyone takes breaks. Start light and build "
            'back up!',
        category: 'training',
        priority: 0.8,
        actionType: 'log_workout',
        actionLabel: 'Start a workout',
      ));
    }

    // 12. Neglected muscle group (from context's neglectedMuscle / lastLegDay etc.)
    final neglectedMuscle = ctx['neglectedMuscle'] as String?;
    final neglectedDays = _intOr(ctx, 'neglectedMuscleDays', 0);
    if (neglectedMuscle != null && neglectedDays >= 10) {
      insights.add(ProactiveInsight(
        message: "You haven't trained $neglectedMuscle in $neglectedDays days. "
            'Consider adding a $neglectedMuscle session to your week.',
        category: 'training',
        priority: 0.55,
        actionType: 'view_exercises',
        actionLabel: 'Browse exercises',
      ));
    }

    // 13. Hit weekly target early
    if (workoutsThisWeek >= workoutTarget && weekday <= 5 && workoutTarget > 0) {
      insights.add(ProactiveInsight(
        message: "You've already hit your $workoutTarget-day workout target "
            "this week and it's only ${_weekdayName(weekday)}! Great work.",
        category: 'motivation',
        priority: 0.35,
      ));
    }

    return insights;
  }

  // ── Body metric insights ───────────────────────────────────────────────

  List<ProactiveInsight> _bodyMetricInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];

    // 14. Weight trend
    final weightTrend = _doubleOr(ctx, 'weightTrend', 0);
    final goal = (ctx['goal'] as String?) ?? '';

    if (weightTrend.abs() >= 0.5) {
      final direction = weightTrend < 0 ? 'down' : 'up';
      final absChange = weightTrend.abs().toStringAsFixed(1);

      final isAlignedWithGoal = (goal.toLowerCase().contains('loss') &&
              weightTrend < 0) ||
          (goal.toLowerCase().contains('gain') && weightTrend > 0) ||
          (goal.toLowerCase().contains('hypertrophy') && weightTrend > 0);

      if (isAlignedWithGoal) {
        insights.add(ProactiveInsight(
          message: 'Your weight has been trending $direction \u2014 '
              "${weightTrend < 0 ? 'you\'ve lost' : 'you\'ve gained'} "
              '${absChange}kg in the last month. Right on track!',
          category: 'motivation',
          priority: 0.4,
          actionType: 'view_progress',
          actionLabel: 'View progress',
        ));
      } else {
        insights.add(ProactiveInsight(
          message: 'Your weight is trending $direction (${absChange}kg this '
              "month). That doesn't align with your $goal goal \u2014 "
              'consider reviewing your nutrition plan.',
          category: 'nutrition',
          priority: 0.65,
          actionType: 'view_progress',
          actionLabel: 'View progress',
        ));
      }
    }

    // 15. No body metrics logged recently
    final daysSinceWeighIn = _intOr(ctx, 'daysSinceLastWeighIn', -1);
    if (daysSinceWeighIn >= 7) {
      insights.add(ProactiveInsight(
        message: "You haven't logged your weight in $daysSinceWeighIn days. "
            'Regular tracking helps you stay on course.',
        category: 'reminder',
        priority: 0.45,
        actionType: 'view_progress',
        actionLabel: 'Log weight',
      ));
    }

    return insights;
  }

  // ── Time-based insights ────────────────────────────────────────────────

  List<ProactiveInsight> _timeBasedInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];
    final hour = DateTime.now().hour;
    final name = (ctx['name'] as String?) ?? '';
    final greeting = name.isNotEmpty ? ', $name' : '';

    // 16. Morning protein tip
    if (hour >= 6 && hour <= 9) {
      final mealsCount = _intOr(ctx, 'todayMealsCount', 0);
      if (mealsCount == 0) {
        insights.add(ProactiveInsight(
          message: 'Good morning$greeting! Start with a protein-rich breakfast '
              'to kickstart your targets.',
          category: 'nutrition',
          priority: 0.4,
          actionType: 'log_meal',
          actionLabel: 'Log breakfast',
        ));
      }
    }

    // 17. Pre-workout meal reminder (afternoon, hasn't eaten recently)
    if (hour >= 14 && hour <= 17) {
      final hoursSinceMeal = _hoursSinceLastMeal(ctx);
      if (hoursSinceMeal >= 3 && !_trainedToday(ctx)) {
        insights.add(ProactiveInsight(
          message: 'Planning to train this evening? Have a light meal with '
              'carbs and protein about 1-2 hours before your workout.',
          category: 'nutrition',
          priority: 0.35,
        ));
      }
    }

    // 18. Usual training day reminder
    final usualTrainingDays = ctx['usualTrainingDays'] as List<int>?;
    if (usualTrainingDays != null) {
      final today = DateTime.now().weekday;
      if (usualTrainingDays.contains(today) && !_trainedToday(ctx)) {
        insights.add(ProactiveInsight(
          message: 'You usually train on ${_weekdayName(today)}s \u2014 '
              "want to plan today's workout?",
          category: 'reminder',
          priority: 0.6,
          actionType: 'log_workout',
          actionLabel: 'Start a workout',
        ));
      }
    }

    // 19. Evening wrap-up
    if (hour >= 20 && hour <= 23) {
      final calTarget = _doubleOr(ctx, 'dailyCalorieTarget', 0);
      final calConsumed = _doubleOr(ctx, 'todayCalories', 0);
      final proteinDeficit = _proteinDeficit(ctx);

      if (calTarget > 0 && calConsumed >= calTarget * 0.9 && calConsumed <= calTarget * 1.05 && proteinDeficit <= 10) {
        insights.add(ProactiveInsight(
          message: 'Great job today$greeting! You hit your calorie and protein '
              'targets. Keep this consistency going.',
          category: 'motivation',
          priority: 0.3,
        ));
      }
    }

    return insights;
  }

  // ── Motivation insights ────────────────────────────────────────────────

  List<ProactiveInsight> _motivationInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];

    // 20. Consecutive weeks hitting workout target
    final consecutiveWeeks = _intOr(ctx, 'consecutiveWeeksOnTarget', 0);
    if (consecutiveWeeks >= 3) {
      insights.add(ProactiveInsight(
        message: "Great consistency! You've hit your workout target "
            '$consecutiveWeeks weeks in a row.',
        category: 'motivation',
        priority: 0.35,
      ));
    }

    // 21. Volume increase
    final volumeChange = _doubleOr(ctx, 'weeklyVolumeChange', 0);
    if (volumeChange >= 10) {
      insights.add(ProactiveInsight(
        message: 'Your training volume is up ${volumeChange.round()}% this '
            'week. Progressive overload in action!',
        category: 'motivation',
        priority: 0.3,
      ));
    }

    // 22. New personal record
    final hasNewPR = ctx['hasNewPR'] == true;
    final prExercise = ctx['prExerciseName'] as String?;
    if (hasNewPR && prExercise != null) {
      insights.add(ProactiveInsight(
        message: 'New personal record on $prExercise! Celebrate the win and '
            'keep pushing.',
        category: 'motivation',
        priority: 0.4,
        actionType: 'view_progress',
        actionLabel: 'View PRs',
      ));
    }

    // 23. Streak-based nudge (memory/pattern aware)
    final memorySummary = (ctx['memorySummary'] as String?) ?? '';
    if (memorySummary.toLowerCase().contains('streak') ||
        memorySummary.toLowerCase().contains('consistent')) {
      insights.add(ProactiveInsight(
        message: "You've been showing great consistency lately. "
            "Don't break the chain!",
        category: 'motivation',
        priority: 0.3,
      ));
    }

    return insights;
  }

  // ── Recovery insights ──────────────────────────────────────────────────

  List<ProactiveInsight> _recoveryInsights(Map<String, dynamic> ctx) {
    final insights = <ProactiveInsight>[];

    // 24. High volume + low protein = poor recovery signal
    final volumeChange = _doubleOr(ctx, 'weeklyVolumeChange', 0);
    final proteinDeficit = _proteinDeficit(ctx);
    if (volumeChange >= 15 && proteinDeficit > 30) {
      insights.add(ProactiveInsight(
        message: 'Your training volume is up but protein intake is low. '
            'Prioritize protein to support recovery and muscle growth.',
        category: 'recovery',
        priority: 0.75,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    // 25. Training every day without rest
    final consecutiveTrainingDays = _intOr(ctx, 'consecutiveTrainingDays', 0);
    if (consecutiveTrainingDays >= 6) {
      insights.add(ProactiveInsight(
        message: "You've trained $consecutiveTrainingDays days in a row. "
            'Rest days are crucial for muscle recovery and growth \u2014 '
            'consider taking one today.',
        category: 'recovery',
        priority: 0.7,
      ));
    }

    // 26. Under-eating on training days
    final calTarget = _doubleOr(ctx, 'dailyCalorieTarget', 0);
    final calConsumed = _doubleOr(ctx, 'todayCalories', 0);
    final trainedToday = _trainedToday(ctx);
    if (trainedToday &&
        calTarget > 0 &&
        calConsumed < calTarget * 0.6 &&
        DateTime.now().hour >= 18) {
      insights.add(ProactiveInsight(
        message: "You trained today but you've only eaten "
            '${calConsumed.round()} of your ${calTarget.round()} kcal target. '
            'Fuel your recovery!',
        category: 'recovery',
        priority: 0.8,
        actionType: 'log_meal',
        actionLabel: 'Log a meal',
      ));
    }

    return insights;
  }

  // ── Helpers ────────────────────────────────────────────────────────────

  double _proteinDeficit(Map<String, dynamic> ctx) {
    final target = _doubleOr(ctx, 'proteinTarget', 0);
    final consumed = _doubleOr(ctx, 'todayProtein', 0);
    return (target - consumed).clamp(0, double.infinity);
  }

  double _calorieOverage(Map<String, dynamic> ctx) {
    final target = _doubleOr(ctx, 'dailyCalorieTarget', 0);
    final consumed = _doubleOr(ctx, 'todayCalories', 0);
    return (consumed - target).clamp(0, double.infinity);
  }

  double _hoursSinceLastMeal(Map<String, dynamic> ctx) {
    final lastMealStr = ctx['lastMealTime'] as String?;
    if (lastMealStr == null || lastMealStr.isEmpty) return 24;
    try {
      final lastMeal = DateTime.parse(lastMealStr);
      return DateTime.now().difference(lastMeal).inMinutes / 60.0;
    } catch (_) {
      return 24;
    }
  }

  int _daysSinceLastWorkout(Map<String, dynamic> ctx) {
    final lastStr = ctx['lastWorkoutDate'] as String?;
    if (lastStr == null || lastStr.isEmpty) return 999;
    try {
      final lastDate = DateTime.parse(lastStr);
      return DateTime.now().difference(lastDate).inDays;
    } catch (_) {
      return 999;
    }
  }

  bool _trainedToday(Map<String, dynamic> ctx) {
    final lastStr = ctx['lastWorkoutDate'] as String?;
    if (lastStr == null || lastStr.isEmpty) return false;
    try {
      final lastDate = DateTime.parse(lastStr);
      final now = DateTime.now();
      return lastDate.year == now.year &&
          lastDate.month == now.month &&
          lastDate.day == now.day;
    } catch (_) {
      return false;
    }
  }

  static String _weekdayName(int weekday) {
    const names = [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ];
    if (weekday >= 1 && weekday <= 7) return names[weekday - 1];
    return 'today';
  }

  static double _doubleOr(Map<String, dynamic> ctx, String key, double fallback) {
    final value = ctx[key];
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is num) return value.toDouble();
    return fallback;
  }

  static int _intOr(Map<String, dynamic> ctx, String key, int fallback) {
    final value = ctx[key];
    if (value is int) return value;
    if (value is double) return value.round();
    if (value is num) return value.round();
    return fallback;
  }
}
